In [ ]:
import numpy as np
np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.random.randint(0, 10 , size=10)

array([0, 3, 3, 3, 4, 0, 9, 0, 8, 0])

In [ ]:
np.random.normal(10, 4, (3,4))

array([[11.12251725, 10.65508318, 12.38479005, 11.18632763],
       [11.00949322,  8.87597725,  5.83104039,  9.53997997],
       [12.98734733, 16.42507401,  9.30046615,  9.93990039]])

In [6]:
np.random.randint(1, 10 , size=9).reshape(3,3)

array([[8, 2, 1],
       [4, 2, 2],
       [1, 3, 2]])

In [10]:
#index seçimi
a = np.random.randint(10, size=10)
a[0:5]

array([1, 7, 7, 4, 3])

In [17]:
m = np.random.randint(10, size=(3,5))
m[2, 3]=2.9 #sadecece 2 yi alır hızlı işlemyapmak adına tek tip değer kullanır
m

array([[9, 3, 8, 9, 8],
       [7, 2, 4, 4, 8],
       [9, 0, 2, 2, 9]])

In [19]:
m[:,3]#bütün saturları seç 0. sütunu seç


array([9, 4, 2])

In [23]:
#fancy index
v = np.arange(0,30,3)
catch = [1,2,3]
v[catch] # v number arrayi catch ifadesi ise bir listedir
#bu işleme fancy index denir

array([3, 6, 9])

In [29]:
#numpy da koşullu işlemler
import numpy as np
v = np.array([1,2,3,4,5])
# 3 den küçük değerlere listeye ekleyen program
#klasik döngü ile
# ab = []
# for i in v:
#   if i<3:
#     ab.append(i)
# ab
#numpy ile

v[v<3]

array([1, 2])

In [34]:
#matematiksel işlemler
import numpy as np
v = np.array([1,2,3,4,5])
#operatörler ile
# v/5
# v*5/10
# v**2
# v-1
#metodlar ile
np.subtract(v, 1)
np.add(v, 1)
np.mean(v)
np.sum(v)
np.min(v)
np.max(v)
np.var(v)

2.0

In [36]:
#numpy ile 2 bilinmeyenli denklem çözümü
#5*x0+x1=12
#x0+3*x1=10
a = np.array([[5,1], [1,3]])#katsayılar
b = np.array([12,10])#çözümler
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [37]:
import numpy as np
a = np.array([2,4,6,8])
print(a**2)

[ 4 16 36 64]
